[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
build-frontend = "build[uv]"


[[tool.cibuildwheel.overrides]]
select = "pp310-macosx_arm64"
inherit.environment = "append"
environment.MACOSX_DEPLOYMENT_TARGET = "14.0"
